spring.application.name=contratos
spring.datasource.url=jdbc:mysql://localhost:3306/CONTRATOS?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=@Nicolas95
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
